### ISSUE TITLE
[Tests] Timeout issue with java hello-world app with run-sw

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#258] opened 2020-05-15 21:39 UTC
Test  languages-java-hello_world-(debug)-(run-sw) 
is failing due to timeout exit code. When looking at logs of enclave I see exit code 0, but enclave doesn't terminate and times out after 300 seconds.

Here is the sample test failure:
https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_TestManagement/Runs?runId=3972&_a=resultSummary&resultId=100000

Here is the last part of log:
```
[[  SGX-LKL ]] lkl_start_init(): lkl_start_kernel() finished
[[  SGX-LKL ]] lkl_start_init(): creating LKL termination thread
[[  SGX-LKL ]] create_lkl_termination_thread(): enter
[[  SGX-LKL ]] lkl_start_init(): calling lkl_mount_virtial()
[[  SGX-LKL ]] lkl_termination_thread(): enter
[[  SGX-LKL ]] lkl_start_init(): calling init_random()
[[  SGX-LKL ]] init_random(): Adding entropy to entropy pool
[[  SGX-LKL ]] lkl_termination_thread(): Performed LKL syscall to get host task allocated (pid=36)
[    0.029724] random: crng init done
[[  SGX-LKL ]] init_enclave_clock(): Setting enclave realtime clock
[    0.031367] virtio_blk virtio1: [vda] 819200 512-byte logical blocks (419 MB/400 MiB)
[    0.138743] software IO TLB: mapped [mem 0x7f89e1456000-0x7f89e5456000] (64MB)
[[  SGX-LKL ]] lkl_mount_disk(): lkl_mount_disk(dev="/dev/vda", mnt="/mnt/vda", ro=0)
[    0.140427] EXT4-fs (vda): mounted filesystem without journal. Opts: 
[[  SGX-LKL ]] lkl_mount_disks(): Set working directory: /
[[  SGX-LKL ]] libc_start_main_stage2(): Calling app main: /usr/bin/java
OpenJDK 64-Bit Server VM warning: Can't detect primordial thread stack location - find_vma failed
Hello SGX world from Java!
[[  SGX-LKL ]] lkl_terminate(): terminating LKL (exit_status=0)
[[  SGX-LKL ]] lkl_termination_thread(): termination thread unblocked
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_sys_chdir(/)
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_umount_timeout(/)
[    1.608042] EXT4-fs (vda): re-mounted. Opts: (null)
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_virtio_netdev_remove()
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_sys_halt()
[    1.608042] reboot: Restarting system
Makefile:29: recipe for target 'run-sw' failed
make run-sw: TIMED OUT after 300 secs
Test run completed with EXIT CODE 124
```

**Comment by hukoyu** [comment] 2020-05-15 21:41
Here is the log file:
[Standard_Console_Output (3).log](https://github.com/lsds/sgx-lkl/files/4637225/Standard_Console_Output.3.log)

**Comment by prp** [comment] 2020-05-16 07:33
This appears to be a new regression that was introduced. What is the earliest commit when you see this?

**Comment by hukoyu** [comment] 2020-05-16 23:33
@prp strangely this passes in the latest PRs. For example:https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=346&view=logs&s=45a4dd8c-d89a-566b-d89f-6724086326ec
This also supports my theory that with @letmaik 's change to run run-sw on regular VMs (instead of sgx-lkl VMs which is very cost effective) but this might be causing some randim timeout failures like that since it might be getting a new VM from Ubuntu pool and downloading docker image and building, running test, may be 5 minutes is not enough sometimes. I am speculating, not sure.

**Comment by letmaik** [comment] 2020-05-17 07:34
@hukoyu Please refer to my comment in https://github.com/lsds/sgx-lkl/pull/250#issuecomment-629434585. Both CI pools (SGX and non-SGX) are setup in exactly the same way. Also, the specific timeout in this issue is clearly from the test itself, not from a job timeout.  The timeout happens during SGX-LKL shutdown (see the logs you posted).

**Comment by hukoyu** [comment] 2020-05-18 07:17
Ok @letmaik I agree. So then the failure is kind of random. It sometimes passes and sometime sfails.

**Comment by letmaik** [comment] 2020-05-18 19:57
@hukoyu Could you please disable this test for now? Many builds are failing because of it.

**Comment by hukoyu** [comment] 2020-05-18 21:48
> @hukoyu Could you please disable this test for now? Many builds are failing because of it.

@letmaik submitted PR https://github.com/lsds/sgx-lkl/pull/263 to disable this test to unblock pipelines.

**Comment by hukoyu** [comment] 2020-05-28 19:18
Looks related to issue https://github.com/lsds/sgx-lkl/issues/283

**Comment by hukoyu** [comment] 2020-06-04 03:24
This issue doesn't repro with latest code. Looks like fixed.

**Comment by SeanTAllen** [comment] 2020-06-04 10:14
@hukoyu I can still repo locally. It just takes some time. I'm still trying to track it down. There's a hang that I can make happen across numerous test apps when given enough time. They may or may not be related.

**Comment by SeanTAllen** [comment] 2020-06-26 17:11
I believe this was fixed by @prp's umount fix.

**Comment by SeanTAllen** [comment] 2020-06-26 18:01
I'm closing this as #551 reenables the test as I believe the umount fix has taken care of this.

**Closed as completed** 2020-07-29 16:22 UTC
Labels: bug, area: samples, p1, needs-triage
