### ISSUE TITLE
LTP tests symlink03 and truncate03 fails with  SIGIOT/SIGABRT

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#768] opened 2020-08-11 18:04 UTC
We reverted patches for tests symlink03 and truncate03 with https://github.com/lsds/ltp/pull/51 after issue lsds/sgx-lkl#297 is fixed 
with PR https://github.com/lsds/sgx-lkl/pull/727

But these two tests are still failing. 

```
truncate03  214  [1;31mTBROK[0m  :  tst_sig.c:234: unexpected signal SIGIOT/SIGABRT(6) received (pid = 36).
truncate03  215  [1;33mTCONF[0m  :  tst_res.c:603: Test needs to be run as root
```

@KenGordon  can you look at that. cc @SeanTAllen 

Log file:
[Standard_Console_Output truncate03.log](https://github.com/lsds/sgx-lkl/files/5058612/Standard_Console_Output.truncate03.log)

**Comment by davidchisnall** [comment] 2020-08-14 10:05
I've filed #787 to track all of the bugs that have the same root cause.  Closing this as a duplicate.

**Closed as completed by davidchisnall** 2020-08-14 10:05 UTC
Labels: needs-triage
