### ISSUE TITLE
Remove directory is failing if directory created with non-root user

### ISSUE THREAD

**Issue by vamsikrishna935** [lsds/sgx-lkl#357] opened 2020-06-01 17:54 UTC
In some original LTP tests some folders are created and removed with (non-root) nobody user.
However this was failing with SGX-LKL. When debugged the folder wasn't created physically although syscall returns success. As a workaround root user used to create folders since these tests are testing chmod and utime and not creating directory. 

Will investitage further but this might be an sgx-lkl bug.

**Comment by hukoyu** [comment] 2020-06-01 19:16
With nobody user remove directory is failing.
/ltp/testcases/kernel/syscalls/chmod/chmod03
/ltp/testcases/kernel/syscalls/chmod/chmod04
/ltp/testcases/kernel/syscalls/utime/utime02
/ltp/testcases/kernel/syscalls/utime/utime05

PR https://github.com/lsds/sgx-lkl/pull/358 is submitted to create and remove directories with root user permission.

**Comment by vamsikrishna935** [comment] 2020-06-30 09:20
@prp : Added code lines and stack trace. Please let me know if anything else needed.
Supporting Code:
https://github.com/linux-test-project/ltp/blob/master/testcases/kernel/syscalls/chmod/chmod03.c#L181

Stack Trace:
```
[[  SGX-LKL ]] libc_start_main_stage2(): Calling app main: /ltp/testcases/kernel/syscalls/chmod/chmod03
[Switching to Thread 0x7fff91f9f700 (LWP 10433)]

Thread 6 "ENCLAVE" hit Breakpoint 1, main (ac=1, av=0x7fff40b5eea0) at chmod03.c:101
101     chmod03.c: No such file or directory.
(gdb) c
Continuing.
chmod03     1  TPASS  :  Functionality of chmod(testfile, 01777) successful
[Switching to Thread 0x7fff8affd700 (LWP 10438)]

Thread 11 "ENCLAVE" hit Breakpoint 2, rmobj (obj=0x7fff40b5f600 "/tmp/chmeePDLb", errmsg=errmsg@entry=0x7fff40b5ed20)
    at tst_tmpdir.c:123
123     tst_tmpdir.c: No such file or directory.
(gdb) bt
#0  rmobj (obj=0x7fff40b5f600 "/tmp/chmeePDLb", errmsg=errmsg@entry=0x7fff40b5ed20) at tst_tmpdir.c:123
#1  0x00007fff3dac46fa in tst_rmdir () at tst_tmpdir.c:328
#2  0x00007fff3dabf653 in cleanup () at chmod03.c:182
#3  main (ac=<optimized out>, av=<optimized out>) at chmod03.c:138
#4  0x00007fff00538402 in libc_start_main_stage2 (main=0x7fff3dabf500 <main>, argc=1, argv=0x7fff40b5eea0)
    at src/env/__libc_start_main.c:168
#5  0x00007fff00538361 in __libc_start_main (main=0x7fff3dabf500 <main>, argc=1, argv=0x7fff40b5eea0)
    at src/env/__libc_start_main.c:153
#6  0x00007fff3dabf6c3 in _start_c (p=<optimized out>) at crt/crt1.c:17
#7  0x00007fff3dabf69b in _start ()
#8  0x0000000000000000 in ?? ()
(gdb) c
Continuing.
chmod03     0  TWARN  :  tst_tmpdir.c:330: tst_rmdir: rmobj(/tmp/chmeePDLb) failed: unlink(/tmp/chmeePDLb) failed; errno=13: EACCES
```
cc @hukoyu

**Comment by prp** [comment] 2020-06-30 11:19
Can you provide a minimum C program that exhibits this problem? Thanks.

**Comment by hukoyu** [comment] 2020-07-06 16:03
@vamsikrishna935 when can you provide the minimum c program @prp is asking for?

**Comment by vamsikrishna935** [comment] 2020-07-22 07:07
Sample code for issue reproducing :
```
#include <signal.h>
#include <pwd.h>
#include "test.h"
#include "safe_macros.h"

char nobody_uid[] = "nobody";
struct passwd *ltpuser;

int main(int ac, char **av)
{
        tst_require_root();

        tst_tmpdir();

        ltpuser = getpwnam(nobody_uid);
        if (ltpuser == NULL)
                tst_brkm(TBROK | TERRNO, NULL, "getpwnam failed");
        SAFE_SETUID(NULL, ltpuser->pw_uid);

        TEST_PAUSE;
        tst_rmdir();
}
```

**Comment by SeanTAllen** [comment] 2020-07-29 15:58
Closing as duplicate of #236.

**Closed as completed by SeanTAllen** 2020-07-29 15:58 UTC
Labels: bug, ltp, cleanup, needs-triage
