### ISSUE TITLE
How to export the application environment variables into sgx-lkl running environment

### ISSUE THREAD

**Issue by Zxiaoyu95** [lsds/sgx-lkl#34] opened 2019-04-01 15:05 UTC
hi ,i don't know how to export the application environment variables when i running application on sgx-lkl,now,i need an application environment variables reference a file in the disk file system,Can you give me some advice? Thank you!

**Comment by cpriebe** [comment] 2019-04-01 15:14
For now you can just pass them to application the same way you would normally. Exported environment variables (or variables provided on the command line) should automatically be available to enclave code.

This is a duplicate of https://github.com/lsds/sgx-lkl/issues/26.

**Closed** 2019-05-21 11:21 UTC

**Comment by ppourali** [comment] 2019-11-19 14:08
Hi, I am also trying to pass export https_proxy variable into the sgx image. Could you please guide me how to do it? I have already set the environment variable in my docker image (from which I create sgx image) but apparently it is not being set.

Thanks.

**Comment by cpriebe** [comment] 2019-11-19 15:16
Hi @ppourali,

At the moment there is no way to embed environment variables into the image. I agree though that this would be a good thing to support.

For testing you can simply provide environment variables on the command line to sgx-lkl-run which are passed on to the enclave. You can also use the --app=path/to/appconfig flag to provide a configuration file that includes environment variables for the enclave (see https://github.com/lsds/sgx-lkl/wiki/Remote-Attestation-and-Remote-Control#remote-control for examples). For secure provisioning, the only supported model right now is to integrate with remote attestation as described here: https://github.com/lsds/sgx-lkl/wiki/Remote-Attestation-and-Remote-Control.

Again, I can see how being able to include runtime configuration in the disk image itself might be useful in some cases. If that's something you need, maybe it would make sense to create a separate issue for that. Obviously, secrets such as the disk encryption key would still have to be provided remotely.

**Comment by ppourali** [comment] 2019-11-19 15:53
Hi @cpriebe,

Thanks for the reply and thanks for the hint. I am trying to provide app config, just to confirm, is the below config file correct?
{
    "run": "/usr/bin/python3",
    "args": [
        "/myapp.py"
    ],
    "environment" : {
        "HTTP_PROXY": "http://USER:PASS@PROXYSERVER:PORT",
        "HTTPS_PROXY":"http://USER:PASS@PROXYSERVER:PORT"
     }
}

I run my image with the following command:
 sgx-lkl-run --app=appconfig.conf ./lkl_image_tf2.img

because it doesn't seem to read the environment variables.

Thanks,
Parsa

> Hi @ppourali,
> 
> At the moment there is no way to embed environment variables into the image. I agree though that this would be a good thing to support.
> 
> For testing you can simply provide environment variables on the command line to sgx-lkl-run which are passed on to the enclave. You can also use the --app=path/to/appconfig flag to provide a configuration file that includes environment variables for the enclave (see https://github.com/lsds/sgx-lkl/wiki/Remote-Attestation-and-Remote-Control#remote-control for examples). For secure provisioning, the only supported model right now is to integrate with remote attestation as described here: https://github.com/lsds/sgx-lkl/wiki/Remote-Attestation-and-Remote-Control.
> 
> Again, I can see how being able to include runtime configuration in the disk image itself might be useful in some cases. If that's something you need, maybe it would make sense to create a separate issue for that. Obviously, secrets such as the disk encryption key would still have to be provided remotely.

**Comment by cpriebe** [comment] 2019-11-19 17:01
Thanks a lot for reporting this. I just reproduced the issue. When using the --app argument, the environment doesn't seem to get set (while it does work when providing the app config remotely). I have just pushed a small change. Maybe you could try again?

```
cd sgx-lkl
git pull
git submodule update
make [...]

$ cat app.conf 
{
"run": "/usr/bin/python3",
"args": [
  "-c",
  "import os;print(os.environ)"
],
"environment" : {
  "HTTP_PROXY": "http://USER:PASS@PROXYSERVER:PORT",
  "HTTPS_PROXY":"http://USER:PASS@PROXYSERVER:PORT"
}
}

$ ./tools/sgx-lkl-disk create --size=80m --alpine=python3 disk.img
$ ./build/sgx-lkl-run --app=./app.conf disk.img
environ({'HTTP_PROXY': 'http://USER:PASS@PROXYSERVER:PORT', 'HTTPS_PROXY': 'http://USER:PASS@PROXYSERVER:PORT'})
```

**Comment by ppourali** [comment] 2019-11-19 18:21
Thanks a lot @cpriebe , it's working perfectly now!

Parsa
