### ISSUE TITLE
LTP tests started failing with Exception SIGSEGV (page fault) received

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#767] opened 2020-08-11 17:15 UTC
Lots of LTP tests started failing with SIGSEGV (page fault) exception. This is a regression.
https://dev.azure.com/sgx-lkl/sgx-lkl/_build/results?buildId=1798&view=results

```
[[  SGX-LKL ]] init_random(): Adding entropy to entropy pool
[    0.130390] random: crng init done
[[  SGX-LKL ]] init_enclave_clock(): Setting enclave realtime clock
[    0.133117] virtio_blk virtio1: [vda] 3072000 512-byte logical blocks (1.57 GB/1.46 GiB)
[[  SGX-LKL ]] lkl_mount_disk(): lkl_mount_disk(dev="/dev/vda", mnt="/mnt/vda", ro=0)
[    0.143260] EXT4-fs (vda): mounted filesystem with ordered data mode. Opts: 
[[  SGX-LKL ]] lkl_mount_disks(): Set working directory: /
[[  SGX-LKL ]] libc_start_main_stage2(): Calling app main: /ltp/testcases/kernel/syscalls/fremovexattr/fremovexattr02
tst_test.c:1106: [1;34mINFO: [0mTimeout per run is 0h 05m 00s
tst_test.c:1125: [1;34mINFO: [0mNo fork support
fremovexattr02.c:73: [1;32mPASS: [0mfremovexattr(2) failed expectedly: ENODATA (61)
fremovexattr02.c:73: [1;32mPASS: [0mfremovexattr(2) failed expectedly: EBADF (9)
[[  SIGNAL  ]] Exception SIGSEGV (page fault) received (code=5 address=0x7f300040b048 opcode=0xf44)
bad count while changing owner
2020-08-11T16:53:59.000000Z [(H)ERROR] tid(0x7f48e2e16700) | :OE_ENCLAVE_ABORTING [/agent/_work/2/s/openenclave/host/calls.c:oe_call_enclave_function_by_table_id:91]
[   SGX-LKL  ] ethread (4: 19) [   SGX-LKL  ] FAIL: sgxlkl_ethread_init() failed (id=4 result=19 (OE_ENCLAVE_ABORTING))
TEST_FAILED EXIT CODE: 1
```

**Comment by hukoyu** [comment] 2020-08-11 17:57
@KenGordon  this looks like related to your latest changes. 

cc @SeanTAllen  @prp @davidchisnall @paulcallen @jxyang

**Comment by davidchisnall** [comment] 2020-08-14 10:04
I've filed #787 to track all of the bugs that have the same root cause.  Closing this as a duplicate.

**Closed as completed by davidchisnall** 2020-08-14 10:04 UTC
Labels: needs-triage
