### ISSUE TITLE
Redis failure under benchmark stress

### ISSUE THREAD

**Issue by daperoni** [lsds/sgx-lkl#681] opened 2020-07-28 00:05 UTC
I am profiling the redis sample code found in sgx-lkl/samples/containers/alpine/. When running the 'redis-benchmark' tool the redis container fails and attempts to connect time out.

Build sample and run using: 
```
SGXLKL_TAP=sgxlkl_tap0 ../../../build/sgx-lkl-run-oe --hw-debug ./sgxlkl-miniroot-fs.img /usr/bin/redis-server --bind 10.0.1.1
```

Output:
```
[   SGX-LKL  ] WARN: WRFSBASE instruction raises SIGILL and will be emulated within the enclave. Run `sgx-lkl-run-oe -t` for information about how to fix this performance issue.
36:C 27 Jul 23:45:11.546 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
36:C 27 Jul 23:45:11.547 # Redis version=4.0.14, bits=64, commit=1e82a561, modified=0, pid=36, just started
36:C 27 Jul 23:45:11.547 # Configuration loaded
36:M 27 Jul 23:45:11.547 * Increased maximum number of open files to 10032 (it was originally set to 1024).
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 4.0.14 (1e82a561/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 36
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

36:M 27 Jul 23:45:11.549 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
36:M 27 Jul 23:45:11.549 # Server initialized
36:M 27 Jul 23:45:11.549 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
36:M 27 Jul 23:45:11.549 * Ready to accept connections

```

Sample benchmark command:
```
sudo redis-benchmark -q -h 10.0.1.1 -c 5 -n 50000
```

Sample output
```
PING_INLINE: 26164.31 requests per second
PING_BULK: 26896.18 requests per second
SET: 26867.28 requests per second
GET: 26968.72 requests per second
INCR: 26723.68 requests per second
LPUSH: 25523.23 requests per second
RPUSH: 27085.59 requests per second
LPOP: 26511.13 requests per second
RPOP: 26343.52 requests per second
SADD: 26525.20 requests per second
HSET: 26068.82 requests per second
SPOP: 27685.49 requests per second
LPUSH (needed to benchmark LRANGE): 26427.06 requests per second
LRANGE_100 (first 100 elements): 48.87098
Writing to socket: Connection timed out
Writing to socket: Connection timed out
```

The server cannot be pinged and refuses further connections.
Failures are related the the number of requests. Increasing the '-n' argument will cause the benchmark to fail on an earlier test.

**Comment by davidchisnall** [comment] 2020-08-03 15:32
May be related: #499

**Comment by davidchisnall** [comment] 2020-08-03 15:53
Thanks for the report.  Marking this as p1, but hopefully it's the same as #499.

**Comment by SeanTAllen** [comment] 2020-08-11 13:34
As of c4885aa7127099c5f95d9a6c86c655b0d93fadb2, I can't reproduce this. However, not for good reasons.

What appears to happen for me is that everything starts off working very well and then first during PING_BULK, the request rate started dropping rapidly. It appears from redis no longer responding but as of now, that is unclear. I killed redis-benchmark and restarted it and PING_INLINE had awful performance where it looks like it managed to send a bit and then it stopped being able to as the rate dropped. Subsequent attempts to run redis-benchmark were worse where it just started at 0.00 for the rate. 

However, I get no output from Redis and/or sgx-lkl indicating any issue.

There's definitely something going on here, it appears to be rather involved.

**Comment by prp** [comment] 2020-08-11 13:39
@SeanTAllen We may have a general issue with the network layer. I suggest to first add a simpler test in which we use something like `iperf` to send different sizes packets between two sockets and check for any loss/problems.

**Comment by SeanTAllen** [comment] 2020-08-11 13:42
@prp that sounds like a reasonable approach. I'm not going any further with this one right now. I took a few spare minutes I had to do a quick triage to see if I could reproduce.

**Comment by daperoni** [comment] 2020-08-11 17:35
> As of [c4885aa](https://github.com/lsds/sgx-lkl/commit/c4885aa7127099c5f95d9a6c86c655b0d93fadb2), I can't reproduce this. However, not for good reasons.
> 
> What appears to happen for me is that everything starts off working very well and then first during PING_BULK, the request rate started dropping rapidly. It appears from redis no longer responding but as of now, that is unclear. I killed redis-benchmark and restarted it and PING_INLINE had awful performance where it looks like it managed to send a bit and then it stopped being able to as the rate dropped. Subsequent attempts to run redis-benchmark were worse where it just started at 0.00 for the rate.
> 
> However, I get no output from Redis and/or sgx-lkl indicating any issue.
> 
> There's definitely something going on here, it appears to be rather involved.

That was the issue I saw. The request rate drops (because new requests time out) and eventually it fails or needs to be canceled. Any further requests to the server, such as those issued through redis-cli, will time out.

**Comment by SeanTAllen** [comment] 2020-08-11 17:38
Thanks for the confirmation @daperoni. That's very good to know. ^5.

**Comment by prp** [comment] 2020-08-11 19:26
@daperoni @SeanTAllen yes, I see the [same](https://github.com/lsds/sgx-lkl/issues/499#issuecomment-672091989) for `iperf`, so it seems that there is the same underlying issue. We should try if we get the same behaviour with a simple client/server socket test. This should make it easier to find the underlying cause.

**Closed as completed** 2020-08-14 19:04 UTC
Labels: p1

**Comment by bodzhang** [comment] 2020-09-16 15:41
@daperoni , did you retest redis performance after "Fix performance collapse in network"  was merged in?

**Comment by daperoni** [comment] 2020-09-16 16:54
Yes, I am not seeing any issues after the fix.
