### ISSUE TITLE
building apps for SGX-LKL on alpine 3.8 (x86-64 syscall 332 is greater than known syscall table length 331)

### ISSUE THREAD

**Issue by fixerivan** [lsds/sgx-lkl#54] opened 2019-07-12 17:51 UTC
as instructed in #49 I build node.js from source (version 12.6.0, without extra config or build parameters) on alpine 3.8 (Linux 4.14.127-0-vanilla)

SGXLKL_ETHREADS=4 SGXLKL_HEAP=1G SGXLKL_KEY=/root/sgx-lkl/build/config/enclave_debug.key sgx-lkl-run disk.img /node /cpubench.js                                                                                              SGX-MUSL-LKL WARN: x86-64 syscall 332 is greater than known syscall table length 331
SGX-MUSL-LKL WARN: x86-64 syscall 332 is greater than known syscall table length 331
SGX-MUSL-LKL WARN: x86-64 syscall 332 is greater than known syscall table length 331
SGX-MUSL-LKL WARN: x86-64 syscall 332 is greater than known syscall table length 331
SGX-MUSL-LKL WARN: x86-64 syscall 332 is greater than known syscall table length 331
SGX-MUSL-LKL WARN: x86-64 syscall 332 is greater than known syscall table length 331
SGX-MUSL-LKL WARN: x86-64 syscall 332 is greater than known syscall table length 331
SGX-MUSL-LKL WARN: x86-64 syscall 332 is greater than known syscall table length 331
fs.js:126
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:513:3)
    at tryReadSync (fs.js:338:20)
    at Object.readFileSync (fs.js:375:19)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:786:22)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/cpubench.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:776:30) {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}
READLINE: WARNING: TURNING OFF OUTPUT FLUSHING

notice the syscall table length warning

also the file is there so why illegal operation on directory:

sgx-lkl-run disk.img /bin/ls -lh /
total 47979
drwxr-xr-x    2 root     root        3.0K Mar  6  2019 bin
-rw-r--r--    1 root     root         324 Jul 12  2019 cpubench.js
drwxr-xr-x    4 root     root           0 Jan  1  1970 dev
drwxr-xr-x   16 root     root        1.0K Jul 12  2019 etc
drwxr-xr-x    2 root     root        1.0K Mar  6  2019 home
drwxr-xr-x    5 root     root        1.0K Jul 12  2019 lib
drwx------    2 root     root       12.0K Jul 12  2019 lost+found
drwxr-xr-x    5 root     root        1.0K Mar  6  2019 media
drwxrwxrwx    2 root     root           0 Jan  1  1970 mnt
-rwxr-xr-x    1 root     root       46.8M Jul 12  2019 node
drwxr-xr-x    3 root     root        1.0K Jul 12  2019 node_modules
-rw-r--r--    1 root     root         332 Jul 12  2019 package-lock.json
dr-xr-xr-x   29 root     root           0 Jan  1  1970 proc
drwx------    4 root     root        1.0K Jul 12  2019 root
drwx------    2 root     root           0 Jan  1  1970 run
drwxr-xr-x    2 root     root        1.0K Mar  6  2019 sbin
drwxr-xr-x    2 root     root        1.0K Mar  6  2019 srv
dr-xr-xr-x   11 root     root           0 Jan  1  1970 sys
drwxrwxrwx    2 root     root           0 Jan  1  1970 tmp
drwxr-xr-x    7 root     root        1.0K Mar  6  2019 usr
drwxr-xr-x   11 root     root        1.0K Mar  6  2019 var

full debug output

SGXLKL_VERBOSE=1 SGXLKL_TRACE_MMAP=1 SGXLKL_TRACE_HOST_SYSCALL=1 SGXLKL_TRACE_LKL_SYSCALL=1 SGXLKL_HD_RW=1 SGXLKL_ETHREADS=4 SGXLKL_HEAP=1G SGXLKL_KEY=/root/sgx-lkl/build/config/enclave_debug.key sgx-lkl-run disk.img /node /cpubench.js

is attached
[debug_out.txt](https://github.com/lsds/sgx-lkl/files/3387455/debug_out.txt)

**Comment by cpriebe** [comment] 2019-07-12 18:00
Hi @fixerivan,

This is the same issue as the one described here: https://github.com/lsds/sgx-lkl/issues/52

I'll see if I can push a fix over the weekend. Should be a simple change.

**Comment by cpriebe** [comment] 2019-07-14 12:57
Duplicate of #52

**Closed** 2019-07-14 14:30 UTC

**Comment by fixerivan** [comment] 2019-07-14 17:26
I confirm that after the most recent patches that you committed today the problem no longer exists

just running any command via skl-run "kills" the shell - output is displayed as it should but with warning:

SGXLKL_HEAP=1G SGXLKL_KEY=/root/sgx-lkl/build/config/enclave_debug.key sgx-lkl-run disk.img /node --version
v12.6.0
READLINE: WARNING: TURNING OFF OUTPUT FLUSHING

after that the console is dead / doesn't accept input, tried bash / sh

forwarding output to file works as a workaround
