### ISSUE TITLE
Various failing tests wrongly assigned to 297

### ISSUE THREAD

**Issue by KenGordon** [lsds/sgx-lkl#772] opened 2020-08-12 13:52 UTC
Some of the tests which have been enabled as part of fixing 297 (lkl_access_ok) still fail. They will be commented out to be fixed as and when. The comment will be "Enable when sgx-lkl github issue 772 is fixed."

**Comment by KenGordon** [comment] 2020-08-12 13:55
report/kernel-syscalls-creat-creat06-(debug)-(run-hw)-(8-ethreads).stdout.txt
	 report/kernel-syscalls-fstatfs-fstatfs02-(debug)-(run-hw)-(8-ethreads).stdout.txt [ unexpected signal SIGSEGV ] 
	 report/kernel-syscalls-read-read02-(debug)-(run-hw)-(8-ethreads).stdout.txt
	 report/kernel-syscalls-clock_gettime-clock_gettime02-(debug)-(run-hw)-(8-ethreads).stdout.txt
	 report/kernel-syscalls-clock_adjtime-clock_adjtime02-(debug)-(run-hw)-(8-ethreads).stdout.txt
	 report/kernel-syscalls-fremovexattr-fremovexattr02-(debug)-(run-hw)-(8-ethreads).stdout.txt
	 report/kernel-syscalls-mknod-mknod06-(debug)-(run-hw)-(8-ethreads).stdout.txt    [ unexpected signal SIGSEGV ] 
	 report/kernel-syscalls-chroot-chroot03-(debug)-(run-hw)-(8-ethreads).stdout.txt  [ unexpected signal SIGSEGV ] 
	 report/kernel-syscalls-lchown-lchown02-(debug)-(run-hw)-(8-ethreads).stdout.txt  [ unexpected signal SIGSEGV ] 
	 report/kernel-syscalls-link-link04-(debug)-(run-hw)-(8-ethreads).stdout.txt      [ unexpected signal SIGSEGV ] 
	 report/kernel-syscalls-clock_settime-clock_settime02-(debug)-(run-hw)-(8-ethreads).stdout.txt
	 report/kernel-syscalls-chown-chown04-(debug)-(run-hw)-(8-ethreads).stdout.txt    [ unexpected signal SIGSEGV ] 
	 report/kernel-syscalls-chmod-chmod06-(debug)-(run-hw)-(8-ethreads).stdout.txt

**Comment by KenGordon** [comment] 2020-08-12 13:55
The chmod one is where a NULL ptr is given as a filename.

**Comment by KenGordon** [comment] 2020-08-13 08:21
/kernel/syscalls/chroot/chroot03 - last one
/kernel/syscalls/clock/settime/clock/settime02 - first one
/kernel/syscalls/mknod/mknod06 - second
/kernel/syscalls/chmod/chmod06 - fourth
/kernel/syscalls/clock/gettime/clock/gettime02 - third on (3 sigsegv) all EFAULT ones?
/kernel/syscalls/link/link04 - 6th
/kernel/syscalls/gettimeofday/gettimeofday02 - NA - times out on my box anyway
/kernel/syscalls/fremovexattr/fremovexattr02 - third
/kernel/syscalls/lchown/lchown02 - third
/kernel/syscalls/chown/chown04 - third
/kernel/syscalls/fstatfs/fstatfs02 - second
/kernel/syscalls/clock/adjtime/clock/adjtime02 - sixth
/kernel/syscalls/creat/creat06 -   fifth

**Comment by davidchisnall** [comment] 2020-08-14 10:04
I've filed #787 to track all of the bugs that have the same root cause.  Closing this as a duplicate.

**Closed as completed by davidchisnall** 2020-08-14 10:04 UTC
Labels: needs-triage
