### ISSUE TITLE
[Tests] LKL bug in do_task_dead() during shutdown

### ISSUE THREAD

**Issue by hukoyu** [lsds/sgx-lkl#413] opened 2020-06-09 21:04 UTC
This test fails a lot:
containers-cc-(nonrelease)-(run-hw)-(8-ethreads)

```
[   SGX-LKL  ] SGX-LKL (OE) 0.2.0-dev (8e0c294) LKL 5.3.0 [NON-RELEASE build (-O3)] [HARDWARE DEBUG]
[   SGX-LKL  ] nproc=4 ETHREADS=4 CMDLINE="mem=32M"
[   SGX-LKL  ] HW TLS support: conf->fsgsbase=1
[   SGX-LKL  ] Registering disk 0 (path='/disk_0.img', mnt='/', [RW    ])
[   SGX-LKL  ] Registering disk 1 (path='/disk_1.img', mnt='/data', [RW    ])
[   SGX-LKL  ] get_signed_libsgxlkl_path... result=/opt/sgx-lkl-nonrelease/bin/../lib/libsgxlkl.so.signed
[   SGX-LKL  ] oe_create_enclave... result=0 (OE_OK)
[   SGX-LKL  ] sgxlkl_enclave_init(ethread_id=0)
[[  SGX-LKL ]] wg0 has public key OcW5UP1vapBV7VKDA4lqmrL/35GdgOYTgYVUgry5Rkw=
[[  SGX-LKL ]] FAIL: Kernel panic! Aborting...
[   SGX-LKL  ] init (0: 19 exit=0) [   SGX-LKL  ] FAIL: sgxlkl_ethread_init() failed (ethread_id=0 result=19 (OE_ENCLAVE_ABORTING))
make: *** [run-hw] Error 1
Failure : 'Kernel panic' observed in 'report/containers-cc-(nonrelease)-(run-hw)-(8-ethreads).stdout.txt' or 'report/containers-cc-(nonrelease)-(run-hw)-(8-ethreads).stderr.txt'
```

Log file:
[Standard_Console_Output (6).log](https://github.com/lsds/sgx-lkl/files/4754850/Standard_Console_Output.6.log)

**Comment by hukoyu** [comment] 2020-06-09 21:08
Other failures:
https://tfsproduks1.visualstudio.com/Ab5352d9a-5ed5-48f2-b767-7f273b55b53c/sgx-lkl/_TestManagement/Runs?runId=10280&_a=resultQuery

**Comment by letmaik** [comment] 2020-06-10 07:14
@hukoyu Test run details aren't accessible publicly (due to DevOps limitations) and some members also don't have access. It would be more useful if you copy paste the relevant part of the log in here if it is different from what you already posted.

```
[    0.628161] reboot: Restarting system
[    0.628161] BUG: failure at kernel/sched/core.c:3898/do_task_dead()!
[    0.628685] Kernel panic - not syncing: BUG!
[    0.628685] ---[ end Kernel panic - not syncing: BUG! ]---
```

**Comment by SeanTAllen** [comment] 2020-06-10 11:14
I did a checkout of `oe_port` using the code as of 25 minutes ago. I did `make` and then tried `SGXLKL_ETHREADS=4 make run-hw`

I get a different error. My OE is from May 29, do I need a more recent version? If not, have dependencies changes in the last couple of weeks?

```
[[  SGX-LKL ]] wg0 has public key WIzivxQYRiKBaSwZ0RBII0N3q8HXRg2cRYgR+fR8KU0=
2020-06-10T11:11:56.000000Z [(H)ERROR] tid(0x7f3645980700) | sgxquoteprovider: libdcap_quoteprov.so libdcap_quoteprov.so: cannot open shared object file: No such file or directory
 [/home/sean/openenclave-sgxlkl/host/sgx/linux/sgxquoteproviderloader.c:oe_load_quote_provider:81]
2020-06-10T11:11:56.000000Z [(H)ERROR] tid(0x7f3645980700) | oe_initialize_quote_provider failed (oe_result_t=OE_QUOTE_PROVIDER_LOAD_ERROR) [/home/sean/openenclave-sgxlkl/host/sgx/sgxquoteprovider.c:oe_initialize_quote_provider:51]
2020-06-10T11:11:56.000000Z [(H)ERROR] tid(0x7f3645980700) | :OE_QUOTE_PROVIDER_LOAD_ERROR [/home/sean/openenclave-sgxlkl/host/sgx/quote.c:sgx_get_qetarget_info:30]
2020-06-10T11:11:56.000000Z [(E)ERROR] tid(0x7f3645980700) | libsgxlkl.so.signed::OE_QUOTE_PROVIDER_LOAD_ERROR [/home/sean/openenclave-sgxlkl/enclave/core/sgx/report.c:oe_get_remote_report:182]
2020-06-10T11:11:56.000000Z [(E)ERROR] tid(0x7f3645980700) | libsgxlkl.so.signed::OE_QUOTE_PROVIDER_LOAD_ERROR [/home/sean/openenclave-sgxlkl/enclave/core/sgx/report.c:_oe_get_report_internal:279]
2020-06-10T11:11:56.000000Z [(E)ERROR] tid(0x7f3645980700) | libsgxlkl.so.signed::OE_QUOTE_PROVIDER_LOAD_ERROR [/home/sean/openenclave-sgxlkl/enclave/core/sgx/report.c:oe_get_report_v2:332]
[[  SGX-LKL ]] FAIL: Failed to retrieve report via oe_get_report_v2: 35.
2020-06-10T11:11:56.000000Z [(H)ERROR] tid(0x7f3645980700) | :OE_ENCLAVE_ABORTING [/home/sean/openenclave-sgxlkl/host/calls.c:oe_call_enclave_function_by_table_id:91]
[   SGX-LKL  ] ethread (1: 19) [   SGX-LKL  ] FAIL: sgxlkl_ethread_init() failed (id=1 result=19 (OE_ENCLAVE_ABORTING))
```

**Comment by letmaik** [comment] 2020-06-10 11:18
@SeanTAllen There's a new runtime dependency as we do dummy quote fetching now. You need to install the Azure DCAP Client library:
```
curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
sudo apt-add-repository https://packages.microsoft.com/ubuntu/$(lsb_release -r -s)/prod
sudo apt install az-dcap-client
```

**Comment by SeanTAllen** [comment] 2020-06-10 11:32
I'm trying to recreate python hello world failure from the attached log file in the original issue comment (which is different than the snippet that is part of the snippet).

```
Execution timeout: 300
Will run tests for run-hw
/opt/sgx-lkl-nonrelease/bin/sgx-lkl-disk create --size=100M --docker=./Dockerfile rootfs.img
Using detected host DNS server in /etc/resolv.conf: 168.63.129.16
Creating rootfs.img from Dockerfile ./Dockerfile...
Building Docker image...
Creating disk image file from Docker container...
Succesfully created rootfs.img.
cp rootfs.img data.img
/opt/sgx-lkl-nonrelease/bin/sgx-lkl-docker build-cc --name=python-helloworld-cc --mode=nonrelease --host-cfg=host-config.json --app-cfg=app-config.json
SGX-LKL root: /opt/sgx-lkl-nonrelease/bin/..
Creating confidential container 'python-helloworld-cc' for nonrelease mode
Using temporary directory sgxlkl_docker_context_KQgw
Sending build context to Docker daemon  209.7MB
Step 1/7 : FROM scratch
 ---> 
Step 2/7 : COPY . /
 ---> d33acb5355d0
Step 3/7 : WORKDIR /tmp
 ---> Running in 54d9fd8b2b2e
Removing intermediate container 54d9fd8b2b2e
 ---> 63b188ac9f26
Step 4/7 : ENV TMPDIR=/tmp
 ---> Running in 46e787bc6c88
Removing intermediate container 46e787bc6c88
 ---> 75d047944d11
Step 5/7 : ENV AZDCAP_CACHE=
 ---> Running in e5b3d34b625f
Removing intermediate container e5b3d34b625f
 ---> 667f89f9b60e
Step 6/7 : ENTRYPOINT ["/opt/sgx-lkl-nonrelease/bin/sgx-lkl-run-oe", "--host-config=/host-cfg.json", "--app-config=/app-cfg.json"]
 ---> Running in 4bd809c00b63
Removing intermediate container 4bd809c00b63
 ---> 9b3d7bd8da6b
Step 7/7 : CMD ["--hw-debug"]
 ---> Running in 27505175065f
Removing intermediate container 27505175065f
 ---> 9a303bb92ea9
Successfully built 9a303bb92ea9
Successfully tagged python-helloworld-cc:latest
Done. Tagged 'python-helloworld-cc'.
touch python-helloworld-cc.stamp
docker run --rm --privileged --network=host -v /opt/sgx-lkl-nonrelease:/opt/sgx-lkl-nonrelease -e SGXLKL_VERBOSE=1 -e SGXLKL_KERNEL_VERBOSE=1 -e SGXLKL_TAP=sgxlkl_tap0 python-helloworld-cc --hw-debug
[    0.000000] Linux version 5.3.0+ (AzDevOps@cisca24ba0000YI) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #1 Tue Jun 9 16:52:03 UTC 2020
[    0.000000] memblock address range: 0x7fcdbe808000 - 0x7fcdc0808000
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 8080
[    0.000000] Kernel command line: mem=32M console=hvc0 virtio_mmio.device=256@0x1000000:1 virtio_mmio.device=273@0x2000000:2
[    0.000000] Dentry cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.000000] Inode-cache hash table entries: 2048 (order: 2, 16384 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory available: 32176k/32768k RAM
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 4096
[    0.000000] lkl: irqs initialized
[    0.000000] clocksource: lkl: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] lkl: time and timers initialized (irq3)
[    0.000000] printk: console [hvc0] enabled
[    0.000000] pid_max: default: 4096 minimum: 301
[    0.000000] Mount-cache hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.000000] Mountpoint-cache hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.003014] devtmpfs: initialized
[    0.005560] random: get_random_bytes called from 0x00007fcd8062f8d9 with crng_init=0
[    0.005560] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.005560] futex hash table entries: 16 (order: -4, 384 bytes, linear)
[    0.005560] xor: automatically using best checksumming function   8regs     
[    0.006785] NET: Registered protocol family 16
[    0.009351] clocksource: Switched to clocksource lkl
[    0.009978] NET: Registered protocol family 2
[    0.009978] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.009978] TCP established hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.009978] TCP bind hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.009978] TCP: Hash tables configured (established 512 bind 512)
[    0.009978] UDP hash table entries: 128 (order: 0, 4096 bytes, linear)
[    0.010561] UDP-Lite hash table entries: 128 (order: 0, 4096 bytes, linear)
[    0.010561] NET: Registered protocol family 1
[    0.010561] virtio-mmio: Registering device virtio-mmio.0 at 0x1000000-0x10000ff, IRQ 1.
[    0.010561] virtio-mmio: Registering device virtio-mmio.1 at 0x2000000-0x2000110, IRQ 2.
[    0.010561] workingset: timestamp_bits=62 max_order=14 bucket_order=0
[    0.011660] NET: Registered protocol family 38
[    0.012186] io scheduler mq-deadline registered
[    0.012732] io scheduler kyber registered
[    0.086547] software IO TLB: mapped [mem 0x7fce0cd0c000-0x7fce10d0c000] (64MB)
[    0.088735] loop: module loaded
[    0.089291] device-mapper: ioctl: 4.40.0-ioctl (2019-01-18) initialised: dm-devel@redhat.com
[    0.096245] wireguard: WireGuard 0.0.20191219 loaded. See www.wireguard.com for information.
[    0.096810] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
[    0.096810] NET: Registered protocol family 10
[    0.097443] Segment Routing with IPv6
[    0.097443] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.098052] This architecture does not have kernel memory protection.
[    0.098052] Run /init as init process
[    0.098871] random: crng init done
[    0.100646] virtio_blk virtio2: [vda] 204800 512-byte logical blocks (105 MB/100 MiB)
[    0.102362] EXT4-fs (vda): mounted filesystem without journal. Opts: 
Hello world!
Network test successful!
[    0.446154] EXT4-fs (vda): re-mounted. Opts: (null)
[    0.446675] reboot: Restarting system
[    0.451665] BUG: failure at kernel/sched/core.c:3898/do_task_dead()!
[    0.451665] Kernel panic - not syncing: BUG!
[    0.452219] ---[ end Kernel panic - not syncing: BUG! ]---
2020-06-09T17:02:25.000000Z [(H)ERROR] tid(0x7fce09500700) | :OE_ENCLAVE_ABORTING [../host/calls.c:oe_call_enclave_function_by_table_id:91]
Makefile:43: recipe for target 'run-hw' failed
make run-hw: FAILED WITH EXIT CODE: 2
Test run completed with EXIT CODE 2
```

I fixed the dependency problem. I can't recreate the issue using

`make` to build
and then `SGXLKL_ETHREADS=4 make run-hw`

Note, my OE is from May 29. Not sure if that might be an issue with recreating.

Ive run the test in a loop for 30 minutes without issue. 

@hukoyu can you try to recreate locally?

**Comment by hukoyu** [comment] 2020-06-10 17:04
> @SeanTAllen There's a new runtime dependency as we do dummy quote fetching now. You need to install the Azure DCAP Client library:
> 
> ```
> curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
> sudo apt-add-repository https://packages.microsoft.com/ubuntu/$(lsb_release -r -s)/prod
> sudo apt install az-dcap-client
> ```

@letmaik is this dependency installed in pipeline now?
I see "kernel-syscalls-getsid-getsid01-(debug)-(run-hw)-(8-ethreads)" test failed with similar error:
```
[[  SGX-LKL ]] sgxlkl_enclave_init(): enter
[[  SGX-LKL ]] sgxlkl_enclave_show_attribute(): enclave base=0x7f4000000000 size=1.043 GB
[[  SGX-LKL ]] sgxlkl_enclave_show_attribute(): enclave heap base=0x7f4000b5b000 size=1024.00 M end=0x7f4040b5b000
[[  SGX-LKL ]] sgxlkl_enclave_init(): calling _dlstart_c()
[[  SGX-LKL ]] _register_enclave_signal_handlers(): Registering OE exception handler...
[[  SGX-LKL ]] lkl_start_init(): kernel command line: 'mem=512m console=hvc0'
[[  SGX-LKL ]] lkl_start_init(): lkl_start_kernel() called
[    0.000000] Linux version 5.3.0+ (AzDevOps@cisca24ba00010H) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #1 Wed Jun 10 16:02:38 UTC 2020
[    0.000000] memblock address range: 0x7f40208da000 - 0x7f40408da000
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 129280
[    0.000000] Kernel command line: mem=512m console=hvc0 virtio_mmio.device=256@0x1000000:1
[    0.000000] Dentry cache hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory available: 516256k/524288k RAM
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] NR_IRQS: 4096
[    0.000000] lkl: irqs initialized
[    0.000000] clocksource: lkl: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
[    0.000000] lkl: time and timers initialized (irq2)
[    0.000531] printk: console [hvc0] enabled
[    0.000531] pid_max: default: 4096 minimum: 301
[    0.000531] Mount-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.000531] Mountpoint-cache hash table entries: 1024 (order: 1, 8192 bytes, linear)
[    0.002753] devtmpfs: initialized
[    0.015254] random: get_random_bytes called from 0x00007f4000675bc4 with crng_init=0
[    0.015254] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.015254] futex hash table entries: 16 (order: -4, 384 bytes, linear)
[    0.015254] xor: automatically using best checksumming function   8regs     
[    0.015757] NET: Registered protocol family 16
[    0.022387] clocksource: Switched to clocksource lkl
[    0.023087] NET: Registered protocol family 2
[    0.023706] tcp_listen_portaddr_hash hash table entries: 256 (order: 0, 4096 bytes, linear)
[    0.023706] TCP established hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.023706] TCP bind hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.023706] TCP: Hash tables configured (established 4096 bind 4096)
[    0.024314] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.024314] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.024869] NET: Registered protocol family 1
[    0.024869] virtio-mmio: Registering device virtio-mmio.0 at 0x1000000-0x10000ff, IRQ 1.
[    0.024869] workingset: timestamp_bits=62 max_order=18 bucket_order=0
[    0.029419] NET: Registered protocol family 38
[    0.029419] io scheduler mq-deadline registered
[    0.029419] io scheduler kyber registered
[    0.114888] software IO TLB: mapped [mem 0x7f40a58c9000-0x7f40a98c9000] (64MB)
[    0.116961] loop: module loaded
[    0.116961] device-mapper: ioctl: 4.40.0-ioctl (2019-01-18) initialised: dm-devel@redhat.com
[    0.121601] wireguard: WireGuard 0.0.20191219 loaded. See www.wireguard.com for information.
[    0.121601] wireguard: Copyright (C) 2015-2019 Jason A. Donenfeld <Jason@zx2c4.com>. All Rights Reserved.
[    0.122160] NET: Registered protocol family 10
[    0.122718] Segment Routing with IPv6
[    0.122718] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.123274] This architecture does not have kernel memory protection.
[    0.128534] Run /init as init process
[[  SGX-LKL ]] lkl_start_init(): lkl_start_kernel() finished
[[  SGX-LKL ]] lkl_start_init(): creating LKL termination thread
[[  SGX-LKL ]] create_lkl_termination_thread(): enter
[[  SGX-LKL ]] lkl_start_init(): calling lkl_mount_virtial()
[[  SGX-LKL ]] lkl_termination_thread(): enter
[[  SGX-LKL ]] lkl_start_init(): calling init_random()
[[  SGX-LKL ]] init_random(): Adding entropy to entropy pool
[[  SGX-LKL ]] lkl_termination_thread(): Performed LKL syscall to get host task allocated (pid=36)
[    0.129092] random: crng init done
[[  SGX-LKL ]] init_enclave_clock(): Setting enclave realtime clock
[    0.193271] virtio_blk virtio1: [vda] 3072000 512-byte logical blocks (1.57 GB/1.46 GiB)
2020-06-10T16:26:47.000000Z [(H)ERROR] tid(0x7f40a10bb700) | :OE_BUFFER_TOO_SMALL [../host/sgx/sgxquote.c:oe_sgx_get_supported_attester_format_ids:109]
Azure Quote Provider: libdcap_quoteprov.so [ERROR]: Could not retreive environment variable for 'AZDCAP_DEBUG_LOG_LEVEL'
[[  SGX-LKL ]] lkl_mount_disk(): lkl_mount_disk(dev="/dev/vda", mnt="/mnt/vda", ro=0)
[    0.199271] EXT4-fs (vda): mounted filesystem with ordered data mode. Opts: 
[[  SGX-LKL ]] lkl_mount_disks(): Set working directory: /
[[  SGX-LKL ]] libc_start_main_stage2(): Calling app main: /ltp/testcases/kernel/syscalls/getsid/getsid01
getsid01    1  [1;32mTPASS[0m  :  session ID is correct
[[  SGX-LKL ]] lkl_terminate(): terminating LKL (exit_status=0)
[[  SGX-LKL ]] lkl_termination_thread(): termination thread unblocked
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_sys_chdir(/)
[[  SGX-LKL ]] lkl_termination_thread(): calling lkl_umount_timeout(/)
``` 
cc @SeanTAllen

**Comment by letmaik** [comment] 2020-06-10 17:27
@hukoyu Yes it is.

**Comment by SeanTAllen** [comment] 2020-06-10 18:15
I was attempting to recreate the issue using the wrong test, I thought from the log that it was for the python-hello world and that the log and snippet were two different instances of failures. I was incorrect on that.

**Comment by letmaik** [comment] 2020-06-11 10:27
@SeanTAllen Please don't look at this test at the moment, it needs a bit of dev docs to run this locally.

**Comment by SeanTAllen** [comment] 2020-06-22 13:24
@hukoyu the title of this issue says 8 ethreads. but the included log is for 4 (see `[   SGX-LKL  ] nproc=4 ETHREADS=4 CMDLINE="mem=32M"`). Is the PR title in error or this was an incorrect log included.

**Comment by SeanTAllen** [comment] 2020-06-22 14:05
I've gotten to here:

```
[    0.103975] Segment Routing with IPv6
[    0.103975] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.104543] This architecture does not have kernel memory protection.
[    0.105100] Run /init as init process
[    0.107917] random: fast init done
[    0.112321] random: crng init done
[[  SGX-LKL ]] wg0 has public key AOZnkSlphJO5wJwz1mnKk0qfXHyLv0DGteSkmPRV/yw=
[   SGX-LKL  ] FAIL: virtio_net_fd_net_tx: write to fd failed: Input/output error2020-06-22T13:53:56.000000Z [(H)ERROR] tid(0x7f9465463700) | :OE_BUFFER_TOO_SMALL [/home/sean/code/lsds/sgx-lkl-2020-06-22-issue-413/openenclave/host/sgx/sgxquote.c:oe_sgx_get_supported_attester_format_ids:109]
```

I can't find anything in the OE docs for how to increase the buffer size, but will continue looking.

**Comment by SeanTAllen** [comment] 2020-06-22 14:33
That code path only gets executed here:
```c
#if defined(OE_LINK_SGX_DCAP_QL)
    result =
        oe_sgx_get_supported_attester_format_ids(format_ids, format_ids_size);
#else
    // No supported format ID
    *format_ids_size = 0;
    result
#endif
```

So its related to the DCAP library and that new dependency triggering a new code path.

I can't as of yet however, figure out how the enclosing function `sgx_get_supported_attester_format_ids` is called.

**Comment by SeanTAllen** [comment] 2020-06-22 17:24
The OE_BUFFER_TOO_SMALL is a red herring.

You can turn off the code triggering that by commenting out this block:

https://github.com/lsds/sgx-lkl/blob/9b94b1b26af1319d66461d67266c5bf1f7e75f4f/src/enclave/enclave_init.c#L155

per @wintersteiger, that is completely ok to do at this point in time.

This is the error you end up with (still virtio input/output error):

```
[    0.120148] NET: Registered protocol family 10
[    0.120706] Segment Routing with IPv6
[    0.125697] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    0.126210] This architecture does not have kernel memory protection.
[    0.126766] Run /init as init process
[    0.127324] random: crng init done
[[  SGX-LKL ]] wg0 has public key z5IzLEPghQJEPdnr7Qa+thrFVIF2P1xWW6k3PumzijI=
[    0.130118] virtio_blk virtio2: [vda] 204800 512-byte logical blocks (105 MB/100 MiB)
[    0.131788] EXT4-fs (vda): mounted filesystem without journal. Opts:
[   SGX-LKL  ] FAIL: virtio_net_fd_net_tx: write to fd failed: Input/output errorMakefile:45: recipe for target 'run-hw' failed
make: *** [run-hw] Error 1
```

**Comment by wintersteiger** [comment] 2020-06-22 17:32
That's right. This error vaguely looks like it could be related to https://github.com/lsds/sgx-lkl/pull/501.

**Comment by prp** [comment] 2020-06-22 17:36
I wonder if this related to https://github.com/lsds/sgx-lkl/issues/499, as this also sometimes fails with `[   SGX-LKL  ] FAIL: virtio_net_fd_net_rx: Write failed: -1`.

**Comment by SeanTAllen** [comment] 2020-06-22 17:53
I stopped getting that error and oddly started getting:

```
touch python-helloworld-cc.stamp
docker run --rm --user 1000 --device /dev/net/tun --network host -v /opt/sgx-lkl:/opt/sgx-lkl -e SGXLKL_VERBOSE=1 -e SGXLKL_KERNEL_VERBOSE=1 -e SGXLKL_TAP=sgxlkl_tap0 -e AZDCAP_DEBUG_LOG_LEVEL=INFO --device /dev/sgx python-helloworld-cc --hw-debug
[   SGX-LKL  ] SGX-LKL (OE) 0.2.0-dev (6a49ff2) LKL 5.3.0 [NON-RELEASE build (-O3)] [HARDWARE DEBUG]
[   SGX-LKL  ] nproc=8 ETHREADS=8 CMDLINE="mem=32M"
[   SGX-LKL  ] HW TLS support: conf->fsgsbase=1
[   SGX-LKL  ] Registering disk 0 (path='disk_0.img', mnt='/', [RW    ])
[   SGX-LKL  ] Registering disk 1 (path='disk_1.img', mnt='/data', [RW    ])
[   SGX-LKL  ] FAIL: Tap device sgxlkl_tap0 unavailable, ioctl("/dev/net/tun"), TUNSETIFF) failed: Operation not permitted
Makefile:49: recipe for target 'run-hw' failed
```

I'm not sure how I got the tap unavailable. Nothing else was running. I ran sgx-lkl-setup again and the test passed. I've run it several more times and it either passed repeatedly or hung somewhere after printing "Network test successful".

**Comment by wintersteiger** [comment] 2020-06-22 19:00
@SeanTAllen this frequently happens to me when there are stray processes running in the background. In my case that usually happens while I work in vscode, which has a timeout (1 sec?) for the gdb cleanup now, so basically whenever it times out, the process keeps running in the background. Rarely, I also have to `kill` gdb or sgx-lkl-run.

**Comment by SeanTAllen** [comment] 2020-06-22 19:07
@wintersteiger that doesn't describe my situation, but its good to know. I checked to make sure I had no stray processes running.

**Comment by SeanTAllen** [comment] 2020-06-23 10:26
@hukoyu after a recent PR from @wintersteiger, I'm no longer able to reproduce this problem. While I can't say that any underlying issue was resolved, I think this can be closed as an issue and reopened if it appears in another way. Can you try reproducing locally with the latest code and see if it works for you as well.

Note, I do sometimes get the shutdown hangs that we experience elsewhere and we haven't found the cause of yet. However, the problem that the issue was opened is no longer reproducible for me.

**Comment by SeanTAllen** [comment] 2020-06-23 12:09
With #509 in place I was able to trigger the 

[    0.628161] reboot: Restarting system
[    0.628161] BUG: failure at kernel/sched/core.c:3898/do_task_dead()!
[    0.628685] Kernel panic - not syncing: BUG!
[    0.628685] ---[ end Kernel panic - not syncing: BUG! ]---

error 1 time. Without #509, I was able to run hundreds of times without seeing it. 

Given that there's a general "can hang a lot" with this test, it seems like this is part of the 1 or more shutdown related issues.

I've only gotten that kernel panic once out of about 50 times so far. It more likely to hang and more likely still to pass.

Here's an example of output from a hang (it took me about 20 runs to get a non-passing):

```
[[  SGX-LKL ]] wg0 has public key gZ5ozzKtF97s4ia3lMWMf0go0wjxmO2NssNgKPolUDo=
[    0.128327] virtio_blk virtio2: [vda] 204800 512-byte logical blocks (105 MB/100 MiB)
[    0.130564] EXT4-fs (vda): mounted filesystem without journal. Opts:
Hello world!
Network test successful!
[    0.493666] EXT4-fs (vda): re-mounted. Opts: (null)
```

**Comment by prp** [comment] 2020-06-23 12:15
@SeanTAllen I wonder if you could add more instrumentation to the BUG error message above to better find out what is going on when this happens.

**Comment by SeanTAllen** [comment] 2020-06-24 14:41
https://github.com/lsds/sgx-lkl/pull/519 fixes the hangs I was seeing with this.

**Comment by hukoyu** [comment] 2020-07-02 21:55
@SeanTAllen is this issue fixed with PR 519? Can I close this issue?

**Closed as completed** 2020-07-06 13:23 UTC
Labels: bug, area: sgx-lkl, p0
